# Help understand what each port means - only returning ports that are available 
# Currently displays PIDs for serivce 01 ONLY (00 - 40)
# Implementation of other modes will be added in the future
class Help:
    def __init__(self):
        self.PortID = {'00': 'PIDs supported (01-20)',
                       '01': 'How many Diagnostic Trouble Codes are there, if any',
                       '02': 'Data prior to Diagnositc Trouble Code occurring',
                       '03': 'Fuel System Status',
                       '04': 'Engine Load',
                       '05': 'Engine Coolant Temp',
                       '06': 'Short Term Fuel Trim (Bank 1)',
                       '07': 'Long Term Fuel Trim (Bank 1)',
                       '08': 'Short Term Fuel Trim (Bank 2)',
                       '09': 'Long Term Fuel Trim (Bank 2)',
                       '0A': 'Fuel pressure',
                       '0B': 'Intake Manifold absolute pressure',
                       '0C': 'Engine speed',
                       '0D': 'Vehicle speed',
                       '0E': 'Timing advance',
                       '0F': 'Intake air temperature',
                       '10': 'Mass Air Flow sensor air flow rate',
                       '11': 'Throttle position',
                       '12': 'Secondary Air status',
                       '13': 'O2 Sensors present (2 Bank)',
                       '14': 'O2 Sensor 1 (Voltage with Short Term Fuel Trim)',
                       '15': 'O2 Sensor 2 (Voltage with Short Term Fuel Trim)' ,
                       '16': 'O2 Sensor 3 (Voltage with Short Term Fuel Trim)',
                       '17': 'O2 Sensor 4 (Voltage with Short Term Fuel Trim)',
                       '18': 'O2 Sensor 5 (Voltage with Short Term Fuel Trim)',
                       '19': 'O2 Sensor 6 (Voltage with Short Term Fuel Trim)',
                       '1A': 'O2 Sensor 7 (Voltage with Short Term Fuel Trim)',
                       '1B': 'O2 Sensor 8 (Voltage with Short Term Fuel Trim)',
                       '1C': 'OBD Standard',
                       '1D': 'O2 Sensors present (4 Bank)',
                       '1E': 'Auxiliary input status',
                       '1F': 'Run time since engine start',
                       '20': 'PIDs supported (21-40)',
                       '21': 'Distance traveled with Check Engine Light on',
                       '22': 'Fuel Rail pressure (relative to manifold vaccum)',
                       '23': 'Fuel Rail Gauge pressue (diesel or gasoline direct injection)',
                       '24': 'O2 Sensor 1 (Air-Fuel Ratio with Voltage)',
                       '25': 'O2 Sensor 2 (Air-Fuel Ratio with Voltage)',
                       '26': 'O2 Sensor 3 (Air-Fuel Ratio with Voltage)',
                       '27': 'O2 Sensor 4 (Air-Fuel Ratio with Voltage)',
                       '28': 'O2 Sensor 5 (Air-Fuel Ratio with Voltage)',
                       '29': 'O2 Sensor 6 (Air-Fuel Ratio with Voltage)',
                       '2A': 'O2 Sensor 7 (Air-Fuel Ratio with Voltage)',
                       '2B': 'O2 Sensor 8 (Air-Fuel Ratio with Voltage)',
                       '2C': 'Exhaust Gas Recirculation',
                       '2D': 'Exhaust Gas Recirculation Error',
                       '2E': 'Evaporative emission purge',
                       '2F': 'Fuel Tank level',
                       '30': 'Warm ups since codes cleared',
                       '31': 'Distance traveled since codes cleared',
                       '32': 'Evaporative Emission System Vapor pressure',
                       '33': 'Absolute Barometric pressure',
                       '34': 'O2 Sensor 1 (Air-Fuel Ratio with Current)',
                       '35': 'O2 Sensor 2 (Air-Fuel Ratio with Current)',
                       '36': 'O2 Sensor 3 (Air-Fuel Ratio with Current)',
                       '37': 'O2 Sensor 4 (Air-Fuel Ratio with Current)',
                       '38': 'O2 Sensor 5 (Air-Fuel Ratio with Current)',
                       '39': 'O2 Sensor 6 (Air-Fuel Ratio with Current)',
                       '3A': 'O2 Sensor 7 (Air-Fuel Ratio with Current)',
                       '3B': 'O2 Sensor 8 (Air-Fuel Ratio with Current)',
                       '3C': 'Catalytic Converter temperature (Bank 1 sensor 1)',
                       '3D': 'Catalytic Converter temperature (Bank 2 sensor 1)',
                       '3E': 'Catalytic Converter temperature (Bank 1 sensor 2)',
                       '3F':'Catalytic Converter temperature (Bank 2 sensor 2)',
                       '40': 'PIDs supported (41-60)',
                       }